# SonarCloud Configuration
sonar.projectKey=FIAP-11SOAT_fase5-video-processing-api
sonar.organization=fiap-11soat
sonar.host.url=https://sonarcloud.io

# Project Information
sonar.projectName=Notification Service
sonar.projectVersion=1.0.0

# Source and test directories
sonar.sources=src/main/java,src/main/resources
sonar.tests=src/test/java

# Java version
sonar.java.source=21

# Coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.codeCoveragePlugin=jacoco

# Exclude generated files and config
sonar.exclusions=**/*CatalogApplication.java,**/config/**,**/dto/**,**/enums/**,**/*ApplicationConstants.java

# Test exclusions
sonar.test.exclusions=**/*Test.java,**/*Tests.java

# Additional exclusions for SonarCloud issues
sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S1602
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e2.ruleKey=java:S125
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e3.ruleKey=java:S2259
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.java

# Quality gate settings
sonar.qualitygate.wait=true