spring.application.name=Video Processing API

aws.s3.bucket.videos=fase5-videos-to-process
aws.s3.bucket.frames=fase5-processed-frames
aws.dynamo.table.videos=fase5-video-processing
aws.sqs.notification=fase5-video-notification-queue

