spring.config.import=optional:aws-secretsmanager:fase5-video-processing-api-secrets

aws.region=us-east-1

# AWS Secrets Manager configuration
spring.cloud.aws.secretsmanager.region=us-east-1
spring.cloud.aws.secretsmanager.enabled=true
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.instance-profile=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# fase5.notification.worker.cognito_jwk_url=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_LOjlx5b3H/.well-known/jwks.json
