aws.region=us-east-1
aws.s3.bucket.videos=fase5-infra-hacka-videos

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

fase5.video_processing_api.auth.jwk={"kty":"RSA","kid":"local-dev-key","use":"sig","alg":"RS256","n":"jNQcXDKQPZaDSsRUy-EukLnHhg4N2M55uB7cdp7ialDELqhNChZ7MsRo8GpGfW8L7tQe8vdX2APvWXkgdRhIVtvBYbGKhIdnpRvRBxJEdRhXRY749BqrA3P8O3v0567Jj4Mq7eD04CGiW_IFQW987Hz0Vvrh9DSHEYtya2hwvkKLtEla57T3stuZzXJqW44Dt-asexYASSngAWi3xH0b-26G1phQ7Mkf9EBC9H0sSCzYG4lYK7jXxhohhFDAQSVpdIEXoeI7eQGGX9KDG2by0Di-ZE1j_1RI8NtwhZiicqzmUXYtX0GvCnmCpjbrZv353Fw1sg_4kbaQUNNvPj3Rrw","e":"AQAB"}
