server.port=8080
spring.application.name=Video Processing API

spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.sqs.endpoint=https://sqs.us-east-1.amazonaws.com
spring.cloud.aws.sqs.enabled=true
# spring.cloud.aws.sqs.listener.execution-mode=blocking

spring.config.import=optional:aws-secretsmanager:fase5-video-processing-api-secrets


aws.dynamo.table.videos=fase5-video-processing
aws.s3.bucket.videos=fase5-videos-to-process
aws.s3.bucket.frames=fase5-processed-frames
aws.sqs.notification=fase5-video-notification-queue


aws.region=us-east-1

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB